inherit_from:
  - .rubocop_hound.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "*.gemspec"
    - "bin/*"
    - "config/initializers/devise.rb"
    - "db/schema.rb"

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false
